name: Android Testing CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Execute Unit Test
        run: ./gradle testDebugUnitTest

      - name: Action Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
